#!/usr/bin/env bash
#Write a Bash script that displays:\
# Trap SIGTERM and handle it with a custom function
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
